server:
  port: 18001

spring:
  application:
    name: mall-service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saas_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


dubbo:
  application:
    name: mall-service-user
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://localhost:8848
