server:
  port: 8081

spring:
  application:
    name: mall-admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

dubbo:
  application:
    name: mall-admin
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
    timeout: 30000

jwt:
  secret: your-256-bit-secret-key-here-must-be-long-enough
  expiration: 7200000

qiniu:
  access-key: xxvsUnHuV849HJWVt5E4hx5ZjR_MWzU1Cj4RA3be
  secret-key:
  bucket: qnhub1
  domain: http://t8nea3kby.hd-bkt.clouddn.com

# 日志配置
logging:
  level:
    cc.oxshan.gateway: DEBUG